#!/bin/bash
#$ -V
#$ -l h_rt=:20:
#$ -pe mpi 16
#$ -cwd
#$ -o Output/
#$ -e Output/Error/
export VT_PFORM_LDIR=.

output=frog/frog_exec


if [[ x$1x == xCOMx ]]; then
	make clean && make
	time mpiexec -n 1 $output
else
	qsub -N PDP_test $0 COM
fi
