#!/bin/bash
#$ -V
#$ -l h_rt=:20:
#$ -cwd
#$ -o Output/
#$ -e Output/Error/
export VT_PFORM_LDIR=.

output=frog/frog_exec

mkdir -p Output/Error 


if [[ x$2x == xCOMx ]]; then
	make -s clean 
	make -s
	args=${@:3:$#}	
	time mpiexec -n $1 $output $args
else
	if [[ -n $1 ]]; then
		NPROC=$1
	else
		NPROC=4
	fi
	args=${@:2:$#}
	qsub -pe mpi $NPROC -N AM_frog $0 $NPROC COM $args
fi
